name:                EyeSpy
version:             0.1.0.0
github:              "GregsAStar/EyeSpy"
license:             BSD3
author:              "Gregory \"GregsAStar\" Mitchell"
maintainer:          "gregmitchell0@protonmail.com"
copyright:           "2019 Gregory \"GregsAStar\" Mitchell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GregsAStar/EyeSpy#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- bmp

library:
  source-dirs: src

executables:
  EyeSpy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EyeSpy

tests:
  EyeSpy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EyeSpy

data-files:
- assets/*